# Yazi - Config
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 2, 4, 3 ]
linemode       = "none"
show_hidden    = true
show_symlink   = true

[preview]
wrap            = "no"
tab_size        = 2

[opener]
append_pdff = [
	{ run = 'zathura "$@"', desc = "zathura", block = true, for = "unix" },
]

[open]
append_rules = [
  { mime = "application/pdf", use = [ "pdff", "reveal" ] },
]
